[package]
name = "dexompiler-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
log = "0.4.21"
regex = "1.10.4"
thiserror = "1.0.58"
zip = "1.1.0"
axmldecoder = { git = "https://github.com/yourlogarithm/axmldecoder.git", version = "0.6.0" }
dex = { git = "https://github.com/yourlogarithm/dex-parser.git", version = "0.5.0" }
env_logger = "0.11.3"
num-derive = "0.4.2"
num-traits = "0.2.18"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
itertools = "0.12.1"
