[package]
name = "dexompiler"
version = "0.1.0"
authors = ["yourlogarithm <vlad.sebastian.cretu.dev@gmail.com>"]
keywords = [
    "dex",
    "decompiler",
    "android",
    "dalvik",
    "art",
    "manifest",
    "axml",
    "apk",
]
repository = "https://github.com/yourlogarithm/dexompiler-rs"
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
log = "0.4.21"
regex = "1.10.4"
thiserror = "1.0.58"
zip = "1.1.0"
axmldecoder = { git = "https://github.com/yourlogarithm/axmldecoder.git", version = "0.6.0" }
dex = { git = "https://github.com/yourlogarithm/dex-parser.git", version = "0.5.0" }
num-derive = "0.4.2"
num-traits = "0.2.18"
serde = { version = "1.0.198", features = ["derive"] }

