[package]
name = "dexompiler"
version = "1.0.0"
authors = ["yourlogarithm <vlad.sebastian.cretu.dev@gmail.com>"]
keywords = [
    "dex",
    "decompiler",
    "android",
    "dalvik",
    "art",
    "manifest",
    "axml",
    "apk",
]
repository = "https://github.com/yourlogarithm/dexompiler-rs"
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
log = "0.4.21"
thiserror = "1.0.58"
zip = "2.1.3"
dex = { git = "https://github.com/yourlogarithm/dex-parser.git", version = "0.5.0" }
regex = "1.10.5"
lazy_static = "1.5.0"

