#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Nop,
    Move,
    MoveFrom16,
    Move16,
    MoveWide,
    MoveWideFrom16,
    MoveWide16,
    MoveObject,
    MoveObjectFrom16,
    MoveObject16,
    MoveResult,
    MoveResultWide,
    MoveResultObject,
    MoveException,
    ReturnVoid,
    Return,
    ReturnWide,
    ReturnObject,
    Const4,
    Const16,
    Const,
    ConstHigh16,
    ConstWide16,
    ConstWide32,
    ConstWide,
    ConstWideHigh16,
    ConstString,
    ConstStringJumbo,
    ConstClass,
    MonitorEnter,
    MonitorExit,
    CheckCast,
    InstanceOf,
    ArrayLength,
    NewInstance,
    NewArray,
    FilledNewArray,
    FilledNewArrayRange,
    FillArrayData,
    Throw,
    Goto,
    Goto16,
    Goto32,
    PackedSwitch,
    SparseSwitch,
    CmplFloat,
    CmpgFloat,
    CmplDouble,
    CmpgDouble,
    CmpLong,
    IfEq,
    IfNe,
    IfLt,
    IfGe,
    IfGt,
    IfLe,
    IfEqz,
    IfNez,
    IfLtz,
    IfGez,
    IfGtz,
    IfLez,
    Aget,
    AgetWide,
    AgetObject,
    AgetBoolean,
    AgetByte,
    AgetChar,
    AgetShort,
    Aput,
    AputWide,
    AputObject,
    AputBoolean,
    AputByte,
    AputChar,
    AputShort,
    Iget,
    IgetWide,
    IgetObject,
    IgetBoolean,
    IgetByte,
    IgetChar,
    IgetShort,
    Iput,
    IputWide,
    IputObject,
    IputBoolean,
    IputByte,
    IputChar,
    IputShort,
    Sget,
    SgetWide,
    SgetObject,
    SgetBoolean,
    SgetByte,
    SgetChar,
    SgetShort,
    Sput,
    SputWide,
    SputObject,
    SputBoolean,
    SputByte,
    SputChar,
    SputShort,
    InvokeVirtual,
    InvokeSuper,
    InvokeDirect,
    InvokeStatic,
    InvokeInterface,
    InvokeVirtualRange,
    InvokeSuperRange,
    InvokeDirectRange,
    InvokeStaticRange,
    InvokeInterfaceRange,
    NegInt,
    NotInt,
    NegLong,
    NotLong,
    NegFloat,
    NegDouble,
    IntToLong,
    IntToFloat,
    IntToDouble,
    LongToInt,
    LongToFloat,
    LongToDouble,
    FloatToInt,
    FloatToLong,
    FloatToDouble,
    DoubleToInt,
    DoubleToLong,
    DoubleToFloat,
    IntToByte,
    IntToChar,
    IntToShort,
    AddInt,
    SubInt,
    MulInt,
    DivInt,
    RemInt,
    AndInt,
    OrInt,
    XorInt,
    ShlInt,
    ShrInt,
    UshrInt,
    AddLong,
    SubLong,
    MulLong,
    DivLong,
    RemLong,
    AndLong,
    OrLong,
    XorLong,
    ShlLong,
    ShrLong,
    UshrLong,
    AddFloat,
    SubFloat,
    MulFloat,
    DivFloat,
    RemFloat,
    AddDouble,
    SubDouble,
    MulDouble,
    DivDouble,
    RemDouble,
    AddInt2Addr,
    SubInt2Addr,
    MulInt2Addr,
    DivInt2Addr,
    RemInt2Addr,
    AndInt2Addr,
    OrInt2Addr,
    XorInt2Addr,
    ShlInt2Addr,
    ShrInt2Addr,
    UshrInt2Addr,
    AddLong2Addr,
    SubLong2Addr,
    MulLong2Addr,
    DivLong2Addr,
    RemLong2Addr,
    AndLong2Addr,
    OrLong2Addr,
    XorLong2Addr,
    ShlLong2Addr,
    ShrLong2Addr,
    UshrLong2Addr,
    AddFloat2Addr,
    SubFloat2Addr,
    MulFloat2Addr,
    DivFloat2Addr,
    RemFloat2Addr,
    AddDouble2Addr,
    SubDouble2Addr,
    MulDouble2Addr,
    DivDouble2Addr,
    RemDouble2Addr,
    AddIntLit16,
    SubIntLit16,
    MulIntLit16,
    DivIntLit16,
    RemIntLit16,
    AndIntLit16,
    OrIntLit16,
    XorIntLit16,
    AddIntLit8,
    SubIntLit8,
    MulIntLit8,
    DivIntLit8,
    RemIntLit8,
    AndIntLit8,
    OrIntLit8,
    XorIntLit8,
    ShlIntLit8,
    ShrIntLit8,
    UshrIntLit8,
    InvokePolymorphic,
    InvokePolymorphicRange,
    InvokeCustom,
    InvokeCustomRange,
    ConstMethodHandle,
    ConstMethodType,
}

impl TryFrom<u8> for Opcode {
    type Error = &'static str;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x0 => Ok(Opcode::Nop),
            0x1 => Ok(Opcode::Move),
            0x2 => Ok(Opcode::MoveFrom16),
            0x3 => Ok(Opcode::Move16),
            0x4 => Ok(Opcode::MoveWide),
            0x5 => Ok(Opcode::MoveWideFrom16),
            0x6 => Ok(Opcode::MoveWide16),
            0x7 => Ok(Opcode::MoveObject),
            0x8 => Ok(Opcode::MoveObjectFrom16),
            0x9 => Ok(Opcode::MoveObject16),
            0xa => Ok(Opcode::MoveResult),
            0xb => Ok(Opcode::MoveResultWide),
            0xc => Ok(Opcode::MoveResultObject),
            0xd => Ok(Opcode::MoveException),
            0xe => Ok(Opcode::ReturnVoid),
            0xf => Ok(Opcode::Return),
            0x10 => Ok(Opcode::ReturnWide),
            0x11 => Ok(Opcode::ReturnObject),
            0x12 => Ok(Opcode::Const4),
            0x13 => Ok(Opcode::Const16),
            0x14 => Ok(Opcode::Const),
            0x15 => Ok(Opcode::ConstHigh16),
            0x16 => Ok(Opcode::ConstWide16),
            0x17 => Ok(Opcode::ConstWide32),
            0x18 => Ok(Opcode::ConstWide),
            0x19 => Ok(Opcode::ConstWideHigh16),
            0x1a => Ok(Opcode::ConstString),
            0x1b => Ok(Opcode::ConstStringJumbo),
            0x1c => Ok(Opcode::ConstClass),
            0x1d => Ok(Opcode::MonitorEnter),
            0x1e => Ok(Opcode::MonitorExit),
            0x1f => Ok(Opcode::CheckCast),
            0x20 => Ok(Opcode::InstanceOf),
            0x21 => Ok(Opcode::ArrayLength),
            0x22 => Ok(Opcode::NewInstance),
            0x23 => Ok(Opcode::NewArray),
            0x24 => Ok(Opcode::FilledNewArray),
            0x25 => Ok(Opcode::FilledNewArrayRange),
            0x26 => Ok(Opcode::FillArrayData),
            0x27 => Ok(Opcode::Throw),
            0x28 => Ok(Opcode::Goto),
            0x29 => Ok(Opcode::Goto16),
            0x2a => Ok(Opcode::Goto32),
            0x2b => Ok(Opcode::PackedSwitch),
            0x2c => Ok(Opcode::SparseSwitch),
            0x2d => Ok(Opcode::CmplFloat),
            0x2e => Ok(Opcode::CmpgFloat),
            0x2f => Ok(Opcode::CmplDouble),
            0x30 => Ok(Opcode::CmpgDouble),
            0x31 => Ok(Opcode::CmpLong),
            0x32 => Ok(Opcode::IfEq),
            0x33 => Ok(Opcode::IfNe),
            0x34 => Ok(Opcode::IfLt),
            0x35 => Ok(Opcode::IfGe),
            0x36 => Ok(Opcode::IfGt),
            0x37 => Ok(Opcode::IfLe),
            0x38 => Ok(Opcode::IfEqz),
            0x39 => Ok(Opcode::IfNez),
            0x3a => Ok(Opcode::IfLtz),
            0x3b => Ok(Opcode::IfGez),
            0x3c => Ok(Opcode::IfGtz),
            0x3d => Ok(Opcode::IfLez),
            0x44 => Ok(Opcode::Aget),
            0x45 => Ok(Opcode::AgetWide),
            0x46 => Ok(Opcode::AgetObject),
            0x47 => Ok(Opcode::AgetBoolean),
            0x48 => Ok(Opcode::AgetByte),
            0x49 => Ok(Opcode::AgetChar),
            0x4a => Ok(Opcode::AgetShort),
            0x4b => Ok(Opcode::Aput),
            0x4c => Ok(Opcode::AputWide),
            0x4d => Ok(Opcode::AputObject),
            0x4e => Ok(Opcode::AputBoolean),
            0x4f => Ok(Opcode::AputByte),
            0x50 => Ok(Opcode::AputChar),
            0x51 => Ok(Opcode::AputShort),
            0x52 => Ok(Opcode::Iget),
            0x53 => Ok(Opcode::IgetWide),
            0x54 => Ok(Opcode::IgetObject),
            0x55 => Ok(Opcode::IgetBoolean),
            0x56 => Ok(Opcode::IgetByte),
            0x57 => Ok(Opcode::IgetChar),
            0x58 => Ok(Opcode::IgetShort),
            0x59 => Ok(Opcode::Iput),
            0x5a => Ok(Opcode::IputWide),
            0x5b => Ok(Opcode::IputObject),
            0x5c => Ok(Opcode::IputBoolean),
            0x5d => Ok(Opcode::IputByte),
            0x5e => Ok(Opcode::IputChar),
            0x5f => Ok(Opcode::IputShort),
            0x60 => Ok(Opcode::Sget),
            0x61 => Ok(Opcode::SgetWide),
            0x62 => Ok(Opcode::SgetObject),
            0x63 => Ok(Opcode::SgetBoolean),
            0x64 => Ok(Opcode::SgetByte),
            0x65 => Ok(Opcode::SgetChar),
            0x66 => Ok(Opcode::SgetShort),
            0x67 => Ok(Opcode::Sput),
            0x68 => Ok(Opcode::SputWide),
            0x69 => Ok(Opcode::SputObject),
            0x6a => Ok(Opcode::SputBoolean),
            0x6b => Ok(Opcode::SputByte),
            0x6c => Ok(Opcode::SputChar),
            0x6d => Ok(Opcode::SputShort),
            0x6e => Ok(Opcode::InvokeVirtual),
            0x6f => Ok(Opcode::InvokeSuper),
            0x70 => Ok(Opcode::InvokeDirect),
            0x71 => Ok(Opcode::InvokeStatic),
            0x72 => Ok(Opcode::InvokeInterface),
            0x74 => Ok(Opcode::InvokeVirtualRange),
            0x75 => Ok(Opcode::InvokeSuperRange),
            0x76 => Ok(Opcode::InvokeDirectRange),
            0x77 => Ok(Opcode::InvokeStaticRange),
            0x78 => Ok(Opcode::InvokeInterfaceRange),
            0x7b => Ok(Opcode::NegInt),
            0x7c => Ok(Opcode::NotInt),
            0x7d => Ok(Opcode::NegLong),
            0x7e => Ok(Opcode::NotLong),
            0x7f => Ok(Opcode::NegFloat),
            0x80 => Ok(Opcode::NegDouble),
            0x81 => Ok(Opcode::IntToLong),
            0x82 => Ok(Opcode::IntToFloat),
            0x83 => Ok(Opcode::IntToDouble),
            0x84 => Ok(Opcode::LongToInt),
            0x85 => Ok(Opcode::LongToFloat),
            0x86 => Ok(Opcode::LongToDouble),
            0x87 => Ok(Opcode::FloatToInt),
            0x88 => Ok(Opcode::FloatToLong),
            0x89 => Ok(Opcode::FloatToDouble),
            0x8a => Ok(Opcode::DoubleToInt),
            0x8b => Ok(Opcode::DoubleToLong),
            0x8c => Ok(Opcode::DoubleToFloat),
            0x8d => Ok(Opcode::IntToByte),
            0x8e => Ok(Opcode::IntToChar),
            0x8f => Ok(Opcode::IntToShort),
            0x90 => Ok(Opcode::AddInt),
            0x91 => Ok(Opcode::SubInt),
            0x92 => Ok(Opcode::MulInt),
            0x93 => Ok(Opcode::DivInt),
            0x94 => Ok(Opcode::RemInt),
            0x95 => Ok(Opcode::AndInt),
            0x96 => Ok(Opcode::OrInt),
            0x97 => Ok(Opcode::XorInt),
            0x98 => Ok(Opcode::ShlInt),
            0x99 => Ok(Opcode::ShrInt),
            0x9a => Ok(Opcode::UshrInt),
            0x9b => Ok(Opcode::AddLong),
            0x9c => Ok(Opcode::SubLong),
            0x9d => Ok(Opcode::MulLong),
            0x9e => Ok(Opcode::DivLong),
            0x9f => Ok(Opcode::RemLong),
            0xa0 => Ok(Opcode::AndLong),
            0xa1 => Ok(Opcode::OrLong),
            0xa2 => Ok(Opcode::XorLong),
            0xa3 => Ok(Opcode::ShlLong),
            0xa4 => Ok(Opcode::ShrLong),
            0xa5 => Ok(Opcode::UshrLong),
            0xa6 => Ok(Opcode::AddFloat),
            0xa7 => Ok(Opcode::SubFloat),
            0xa8 => Ok(Opcode::MulFloat),
            0xa9 => Ok(Opcode::DivFloat),
            0xaa => Ok(Opcode::RemFloat),
            0xab => Ok(Opcode::AddDouble),
            0xac => Ok(Opcode::SubDouble),
            0xad => Ok(Opcode::MulDouble),
            0xae => Ok(Opcode::DivDouble),
            0xaf => Ok(Opcode::RemDouble),
            0xb0 => Ok(Opcode::AddInt2Addr),
            0xb1 => Ok(Opcode::SubInt2Addr),
            0xb2 => Ok(Opcode::MulInt2Addr),
            0xb3 => Ok(Opcode::DivInt2Addr),
            0xb4 => Ok(Opcode::RemInt2Addr),
            0xb5 => Ok(Opcode::AndInt2Addr),
            0xb6 => Ok(Opcode::OrInt2Addr),
            0xb7 => Ok(Opcode::XorInt2Addr),
            0xb8 => Ok(Opcode::ShlInt2Addr),
            0xb9 => Ok(Opcode::ShrInt2Addr),
            0xba => Ok(Opcode::UshrInt2Addr),
            0xbb => Ok(Opcode::AddLong2Addr),
            0xbc => Ok(Opcode::SubLong2Addr),
            0xbd => Ok(Opcode::MulLong2Addr),
            0xbe => Ok(Opcode::DivLong2Addr),
            0xbf => Ok(Opcode::RemLong2Addr),
            0xc0 => Ok(Opcode::AndLong2Addr),
            0xc1 => Ok(Opcode::OrLong2Addr),
            0xc2 => Ok(Opcode::XorLong2Addr),
            0xc3 => Ok(Opcode::ShlLong2Addr),
            0xc4 => Ok(Opcode::ShrLong2Addr),
            0xc5 => Ok(Opcode::UshrLong2Addr),
            0xc6 => Ok(Opcode::AddFloat2Addr),
            0xc7 => Ok(Opcode::SubFloat2Addr),
            0xc8 => Ok(Opcode::MulFloat2Addr),
            0xc9 => Ok(Opcode::DivFloat2Addr),
            0xca => Ok(Opcode::RemFloat2Addr),
            0xcb => Ok(Opcode::AddDouble2Addr),
            0xcc => Ok(Opcode::SubDouble2Addr),
            0xcd => Ok(Opcode::MulDouble2Addr),
            0xce => Ok(Opcode::DivDouble2Addr),
            0xcf => Ok(Opcode::RemDouble2Addr),
            0xd0 => Ok(Opcode::AddIntLit16),
            0xd1 => Ok(Opcode::SubIntLit16),
            0xd2 => Ok(Opcode::MulIntLit16),
            0xd3 => Ok(Opcode::DivIntLit16),
            0xd4 => Ok(Opcode::RemIntLit16),
            0xd5 => Ok(Opcode::AndIntLit16),
            0xd6 => Ok(Opcode::OrIntLit16),
            0xd7 => Ok(Opcode::XorIntLit16),
            0xd8 => Ok(Opcode::AddIntLit8),
            0xd9 => Ok(Opcode::SubIntLit8),
            0xda => Ok(Opcode::MulIntLit8),
            0xdb => Ok(Opcode::DivIntLit8),
            0xdc => Ok(Opcode::RemIntLit8),
            0xdd => Ok(Opcode::AndIntLit8),
            0xde => Ok(Opcode::OrIntLit8),
            0xdf => Ok(Opcode::XorIntLit8),
            0xe0 => Ok(Opcode::ShlIntLit8),
            0xe1 => Ok(Opcode::ShrIntLit8),
            0xe2 => Ok(Opcode::UshrIntLit8),
            0xfa => Ok(Opcode::InvokePolymorphic),
            0xfb => Ok(Opcode::InvokePolymorphicRange),
            0xfc => Ok(Opcode::InvokeCustom),
            0xfd => Ok(Opcode::InvokeCustomRange),
            0xfe => Ok(Opcode::ConstMethodHandle),
            0xff => Ok(Opcode::ConstMethodType),
            _ => Err("Invalid opcode")
        }
    }
}
